apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-helm-test-production
  namespace: flux-system
spec:
  interval: 1m
  path: "./environments/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-helm-test
