apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-production
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/frontend-chart
      sourceRef:
        kind: GitRepository
        name: flux-helm-test
        namespace: flux-system
  values:
    name: frontend-production
    replicaCount: 2
    image:
      repository: gonvazquez/frontend-production
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      port: 80
