apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-production
  namespace: default
spec:
  interval: 1m
  releaseName: frontend-production
  chart:
    spec:
      chart: nginx
      version: "15.2.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: gonvazquez/frontend-production
      tag: latest
    service:
      type: LoadBalancer
    replicaCount: 2
