apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-testing
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/frontend-chart
      sourceRef:
        kind: GitRepository
        name: flux-helm-test
        namespace: flux-system
      interval: 1m
  values:
    name: frontend-testing
    replicaCount: 1
    image:
      repository: gonvazquez/frontend-testing
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      port: 80
