apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-testing
  namespace: default
spec:
  interval: 1m
  releaseName: nginx-testing
  chart:
    spec:
      chart: nginx
      version: "15.2.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
    replicaCount: 1
