apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend-testing
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/frontend-chart
      sourceRef:
        kind: GitRepository
        name: flux-helm-test
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: frontend-testing-values
